In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
breastCancer = pd.read_csv('Breast_cancer.csv')

In [3]:
breastCancer.head()

mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0        17.99         10.38  ...          0.11840          0
1        20.57         17.77  ...          0.08474          0
2        19.69         21.25  ...          0.10960          0
3        11.42         20.38  ...          0.14250          0
4        20.29         14.34  ...          0.10030          0

[5 rows x 6 columns]

In [4]:
print(breastCancer)

     mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0          17.99         10.38  ...          0.11840          0
1          20.57         17.77  ...          0.08474          0
2          19.69         21.25  ...          0.10960          0
3          11.42         20.38  ...          0.14250          0
4          20.29         14.34  ...          0.10030          0
..           ...           ...  ...              ...        ...
564        21.56         22.39  ...          0.11100          0
565        20.13         28.25  ...          0.09780          0
566        16.60         28.08  ...          0.08455          0
567        20.60         29.33  ...          0.11780          0
568         7.76         24.54  ...          0.05263          1

[569 rows x 6 columns]


In [5]:
breastCancer = breastCancer.to_numpy()

In [6]:
print(breastCancer)

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 0.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 0.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 0.000e+00]
 ...
 [1.660e+01 2.808e+01 1.083e+02 8.581e+02 8.455e-02 0.000e+00]
 [2.060e+01 2.933e+01 1.401e+02 1.265e+03 1.178e-01 0.000e+00]
 [7.760e+00 2.454e+01 4.792e+01 1.810e+02 5.263e-02 1.000e+00]]


In [7]:
dataTrain = np.concatenate((breastCancer[0:200, :], breastCancer[300:500, :]),
                           axis=0)
dataTest = np.concatenate((breastCancer[200:300, :], breastCancer[500:569, :]),
                          axis=0)

In [8]:
print(dataTrain)
len(dataTrain)

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 0.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 0.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 0.000e+00]
 ...
 [1.247e+01 1.731e+01 8.045e+01 4.801e+02 8.928e-02 1.000e+00]
 [1.849e+01 1.752e+01 1.213e+02 1.068e+03 1.012e-01 0.000e+00]
 [2.059e+01 2.124e+01 1.378e+02 1.320e+03 1.085e-01 0.000e+00]]


400

In [9]:
print(dataTest)
len(dataTest)

[[1.223e+01 1.956e+01 7.854e+01 4.610e+02 9.586e-02 1.000e+00]
 [1.754e+01 1.932e+01 1.151e+02 9.516e+02 8.968e-02 0.000e+00]
 [2.329e+01 2.667e+01 1.589e+02 1.685e+03 1.141e-01 0.000e+00]
 ...
 [1.660e+01 2.808e+01 1.083e+02 8.581e+02 8.455e-02 0.000e+00]
 [2.060e+01 2.933e+01 1.401e+02 1.265e+03 1.178e-01 0.000e+00]
 [7.760e+00 2.454e+01 4.792e+01 1.810e+02 5.263e-02 1.000e+00]]


169

In [10]:
inputTrain = dataTrain[:, 0:5]
inputTest = dataTest[:, 0:5]
labelTrain = dataTrain[:, 5]
labelTest = dataTest[:, 5]
print(labelTrain)
len(labelTrain)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1.
 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

400

In [11]:
model = tree.DecisionTreeClassifier()

In [12]:
model = model.fit(inputTrain, labelTrain)

In [13]:
hasilPrediksi = model.predict(inputTest)
print("Label Sebenarnya : ", labelTest)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.
 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.
 1.]
Hasil Prediksi :  [1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.
 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1.
 0. 0. 1

In [14]:
prediksiBenar = (hasilPrediksi == labelTest).sum()
prediksiSalah = (hasilPrediksi != labelTest).sum()
print("Prediksi Benar = ", prediksiBenar, "data")
print("Prediksi Salah = ", prediksiSalah, "data")
print("Akurasi = ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar =  154 data
Prediksi Salah =  15 data
Akurasi =  91.12426035502959 %
