In [24]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


In [25]:
dataset = pd.read_csv('3.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [26]:
print(x)

[['Marto' 44.0 7200000.0]
 ['Sinta' 27.0 4800000.0]
 ['Dito' 30.0 5400000.0]
 ['Sinta' 38.0 6100000.0]
 ['Dito' 40.0 nan]
 ['Marto' 35.0 5800000.0]
 ['Sinta' nan 5200000.0]
 ['Marto' 48.0 7900000.0]
 ['Dito' 50.0 8300000.0]
 ['Marto' 37.0 6700000.0]]


In [27]:
print(y)

['Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya']


In [28]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [29]:
print(x)

[['Marto' 44.0 7200000.0]
 ['Sinta' 27.0 4800000.0]
 ['Dito' 30.0 5400000.0]
 ['Sinta' 38.0 6100000.0]
 ['Dito' 40.0 6377777.777777778]
 ['Marto' 35.0 5800000.0]
 ['Sinta' 38.77777777777778 5200000.0]
 ['Marto' 48.0 7900000.0]
 ['Dito' 50.0 8300000.0]
 ['Marto' 37.0 6700000.0]]


In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [31]:
print(x)

[[0.0 1.0 0.0 44.0 7200000.0]
 [0.0 0.0 1.0 27.0 4800000.0]
 [1.0 0.0 0.0 30.0 5400000.0]
 [0.0 0.0 1.0 38.0 6100000.0]
 [1.0 0.0 0.0 40.0 6377777.777777778]
 [0.0 1.0 0.0 35.0 5800000.0]
 [0.0 0.0 1.0 38.77777777777778 5200000.0]
 [0.0 1.0 0.0 48.0 7900000.0]
 [1.0 0.0 0.0 50.0 8300000.0]
 [0.0 1.0 0.0 37.0 6700000.0]]


In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [33]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [35]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 5200000.0]
 [1.0 0.0 0.0 40.0 6377777.777777778]
 [0.0 1.0 0.0 44.0 7200000.0]
 [0.0 0.0 1.0 38.0 6100000.0]
 [0.0 0.0 1.0 27.0 4800000.0]
 [0.0 1.0 0.0 48.0 7900000.0]
 [1.0 0.0 0.0 50.0 8300000.0]
 [0.0 1.0 0.0 35.0 5800000.0]]


In [36]:
print(x_test)

[[1.0 0.0 0.0 30.0 5400000.0]
 [0.0 1.0 0.0 37.0 6700000.0]]


In [37]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [38]:
print(y_test)

[0 1]


In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [40]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412427]
 [1.0 0.0 0.0 -0.014117293757057777 -0.07013167641635393]
 [0.0 1.0 0.0 0.566708506533324 0.6335624327104549]
 [0.0 0.0 1.0 -0.30453019390224867 -0.3078661727429788]
 [0.0 0.0 1.0 -1.9018011447007988 -1.4204636155515822]
 [0.0 1.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 -0.7401495441200351 -0.5646194287757333]]


In [41]:
print(x_test)

[[1.0 0.0 0.0 -1.4661817944830124 -0.906957103486073]
 [0.0 1.0 0.0 -0.44973664397484414 0.2056403393225305]]
